New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Machine__c</fullName>
        <description>Please specify the machine model here</description>
        <label>Machine</label>
        <picklist>
            <controllingField>Machine_Status__c</controllingField>
            <picklistValues>
                <fullName>Smach 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 1500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 152</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 161</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 430</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Machine_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine Inventory</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Purchase__c.object
<CustomObject>
    <description>This object captures the details of initial costs borne by Frosty Boy to purchase machines/spare parts. ‘Purchases’ object is loosely coupled with the ‘Machines’ object to identify for which machine the purchase was made. This is being kept a separate object since spare parts would be the same (unserialized), but purchases will be made frequently.</description>
    <fields>
        <fullName>Machine__c</fullName>
        <label>Item</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Spare_Parts_Used__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Spare Parts Used</relationshipLabel>
        <relationshipName>Spare_Parts_Used</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <label>Spare Part</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Spare Parts Used</relationshipLabel>
        <relationshipName>Spare_Parts_Used</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Spare Parts Used</label>
    <nameField>
        <displayFormat>SPU-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spare Parts Used</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_AddSparePartsController_TestClass.cls
@isTest(seealldata=false)
private class FB_AddSparePartsController_TestClass {
	private static case caseInstance;
	private static Machine__c machine,sparePart;
	private static Machine_inventory__c inventory;
	private static Account customer;
	private static FB_AddSparePartsController controller;
	private static Spare_Parts_used__c sparePartUsed;
	private static Purchase__c newPurchase;
	static void init(){
		//machine=new Machine__c();
		//sparePart=new Machine__c();
		customer=FB_InitializeTestData.createAccount('TestCustomer');
		customer.type='Machine Customer';
		database.insert(customer);
		 machine=FB_InitializeTestData.createMachine('TEST128766');
		 database.insert(machine);
		 inventory=FB_InitializeTestData.createMachineInventory(machine.id,customer.id);
		 database.insert(inventory);
		caseInstance=FB_InitializeTestData.createCase(inventory.id);
		database.insert(caseInstance);
		controller=new FB_AddSparePartsController(new ApexPages.StandardController(caseInstance));
		
		 sparePart=FB_InitializeTestData.createMachine('TEST1233');
		 sparePart.RecordTypeId =[select id,name from recordtype where sobjecttype='Machine__c' and name='Spare Part'].id;
		 database.insert(sparePart);
			
		sparePartUsed=new Spare_Parts_used__c();
		sparePartUsed.Case__c=caseInstance.id;
		sparePartUsed.Spare_Part__c=sparePart.id;
		sparePartUsed.Quantity__c=0;		
		database.insert(sparePartUsed);
		//System.assertEquals([select id from machine__c where id=:sparePart.id],null);
	}
    static testMethod void myUnitTest() { 
        // TO DO: implement unit test
        
        Test.startTest();
        init();
        System.assertEquals(controller.addSparePart(),null);
        controller.newSparePart.Spare_Part__c=sparePart.id;
        System.assertEquals(controller.save(),null);
        
        System.assertNotEquals(controller.getTableValues() , null);
        System.assertNotEquals(controller.getPageURL(),null);
        Test.stopTest();
        
    }
    
}