New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_ConvertLead_TestClass.cls
@isTest(seeAlldata = true)
public class FB_ConvertLead_TestClass
{
    static Lead childLead;
    static Account parentAccount;
    static Account childAccount;
    public static void init()
    {
        parentAccount = FB_InitializeTestData.createAccount('ParentAccount');
        parentAccount.Type = 'Distributor';   
        parentAccount.Primary_Email__c = 'Name@Company.com';
        database.insert(parentAccount);
        childLead = FB_InitializeTestData.createLead();
        childLead.Parent_Account__c = parentAccount.Id;
        childLead.Email = 'Lead@Company.com';
        childLead.Description = 'ABC';
        database.insert(childLead);
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(childLead .id);
        lc.setDoNotCreateOpportunity(true);
        lc.setConvertedStatus('Lead');
        Database.LeadConvertResult lcr = Database.convertLead(lc);
               
    }
    static testmethod void testCaseSimple()
    {
        init();
    }
}