New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Category__c</fullName>
        <description>Enter here the Business Category</description>
        <label>Business Category</label>
        <picklist>
            <controllingField>Classification__c</controllingField>
            <picklistValues>
                <fullName>Bakery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cafe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frozen Yoghurt Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ice Cream Parlor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Juice Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mining Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pub/Clubs/Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theme Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frozen Yoghurt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toppings &amp; Syrups</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <description>Complete here if the New Account is a Lead</description>
        <label>Interested in</label>
        <picklist>
            <controllingField>Account_Status__c</controllingField>
            <picklistValues>
                <fullName>Soft-Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frozen Yoghurt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toppings and Syrups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frosty Ice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service and Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment &amp; Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <picklist>
            <picklistValues>
                <fullName>Frozen Yoghurt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toppings&amp;Syrups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milk Powder Pks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/classes/NotifyOpportunity.cls
global class NotifyOpportunity
{
    Webservice static String SendNotificationMail(String oppId)
    {
     String messageBody;
        String emailAddress;
        Opportunity opp = [select AccountId,Name,CreatedBy.Name,Account.Name,Description,StageName,CloseDate,Product_Group__c from Opportunity where Id = :oppId];
        Account currentAccount = [select ParentId,Name,Interested_In__c,Business_Category__c,Description from Account where Id = :opp.AccountId];
        Account parentAccount = [select Name,Type, primary_email__c from Account where Id = :currentAccount.ParentId];
        Messaging.SingleEmailMessage notificationMail = new Messaging.SingleEmailMessage(); 
        List<String> toAddresses = new List<String>();
        emailAddress=(String)parentAccount.Primary_Email__c;
        toAddresses.add(emailAddress);
        notificationMail.setToAddresses(toAddresses);
        notificationMail.setSubject('New opportunity linked to one of your accounts');
        messageBody='<html><body>Hi  '+parentAccount.Name+',<br/><br/>This mail is to inform that a new opportunity '+ opp.Name + ' has been linked with one of your clients.<br></br>Opportunity Information are as follows:<br/> Created by: '+ opp.CreatedBy.Name + '<br/> Client Name: '+ opp.Account.Name + '<br/>Opportunity Description: '+opp.Description +'<br/> Opportunity Stage: '+ opp.StageName+ '<br/>Opportunity Closed Date : '+opp.CloseDate.format() +'<br/> Product Group : '+ opp.Product_Group__c + '<body></html>';
        notificationMail.setHtmlBody(messageBody);
        notificationMail.setSaveAsActivity(true);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { notificationMail});  
        return 'success';
    }
}