New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Machine__c</fullName>
        <description>Please specify the machine model here</description>
        <label>Machine</label>
        <picklist>
            <controllingField>Machine_Status__c</controllingField>
            <picklistValues>
                <fullName>Smach 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 1500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 152</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 161</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 430</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <fields>
        <fullName>Billing_Date__c</fullName>
        <label>Billing Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sale_price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Monthly Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated-Cool Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Monthly_Payment__c.object
<CustomObject>
    <description>This object tracks the monthly payments expected from a machine location (only if Rent/FOL). If a machine is at a location and is active , a new record is created at the start of the month using a batch class. it populates the expected revenue from that machine this month and possibly creates a task against the owner to follow up on the invoice at the end of the month.</description>
    <fields>
        <fullName>Machine_Location__c</fullName>
        <label>Machine Location</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Monthly Payments</relationshipLabel>
        <relationshipName>Monthly_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <label>Monthly Payment</label>
    <nameField>
        <label>Monthly Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_GenerateMonthlyPayments_TestClass.cls
@isTest(seealldata=false)
private class FB_GenerateMonthlyPayments_TestClass {
    private static List<Machine__c> machineList;
    private static List<Machine_Inventory__c> machineLocationList;
    private static List<Monthly_Payment__c> monthlyPaymentList;
    private static Monthly_Payment__c payment;
    private static Account customer;
    private static List<String> machineLocationIds;
    static void init(){
    	machineLocationIds=new List<String>();
    	machineList=new List<Machine__c>();
    	payment=new Monthly_Payment__c();
    	machineLocationList=new List<Machine_Inventory__c>();
    	monthlyPaymentList=new List<Monthly_Payment__c>();
    	
    	for(Integer i=0;i<50;i++){
    		machineList.add(FB_InitializeTestData.createMachine(String.valueOf(i)));
    	}
    	Database.Insert(machineList);
    	customer=FB_InitializeTestData.createAccount('TestName');
    	customer.Type='Machine Customer';
    	Database.Insert(customer);
    	for(Machine__c newInstance:machineList){
    		Machine_Inventory__c newMachineLocation=FB_InitializeTestData.createMachineInventory(newInstance.id,customer.id);
    		newMachineLocation.Billing_Date__c=date.today()-365;
    		newMachineLocation.End_Date__c=Date.today()+365;
    		machineLocationList.add(newMachineLocation);
    	}
    	Database.Insert(machineLocationList);
    	for(machine_Inventory__c newLocation:machineLocationList){
    		monthlyPaymentList.add(FB_InitializeTestData.createMonthlyPayments(newLocation.id,'TestPayment'+newLocation.Id));
    		machineLocationIds.add(newLocation.id);
    	}
    	
    	//
    	
    	
    }
    static testMethod void generatePaymentsIfNotThereFromBillStartDate(){
    	
          //System.debug(query);
    	Test.startTest();
    	init();
    	String query='select Id,Name,Sale_price__c,Billing_Date__c,End_Date__c,(select id,month__c,Machine_Location__c from Monthly_Payments__r order by month__c desc) from Machine_Inventory__c where status__c=\'Allocated\' AND Billing_Date__c<='+String.valueOf(date.today())+' AND Id IN (';
          for(String location:machineLocationIds){
              query= query+ '\''+location+'\',';
            }
          query = query.substring(0, query.length()-1)+')';
    	FB_GenerateMonthlyPayments generatePayment=new FB_GenerateMonthlyPayments(machineLocationIds,'Allocated');
    	generatePayment.query=query;
    	ID batchid = Database.executeBatch(generatePayment);
        Test.stopTest();
    }
    
    static testMethod void generatePaymentsIfNotThereFromLastBilledDate(){
        Test.startTest();
        init();
    database.insert(monthlyPaymentList);
        String query='select Id,Name,Sale_price__c,Billing_Date__c,End_Date__c,(select id,month__c,Machine_Location__c from Monthly_Payments__r order by month__c desc) from Machine_Inventory__c where status__c=\'Allocated\' AND Billing_Date__c<='+String.valueOf(date.today())+' AND Id IN (';
          for(String location:machineLocationIds){
              query= query+ '\''+location+'\',';
            }
          query = query.substring(0, query.length()-1)+')';
    	FB_GenerateMonthlyPayments generatePayment=new FB_GenerateMonthlyPayments(machineLocationIds,'Allocated');
    	generatePayment.query=query;
        ID batchid2 = Database.executeBatch(generatePayment);
        Test.stopTest();
    }
}