New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Machine__c</fullName>
        <description>Please specify the machine model here</description>
        <label>Machine</label>
        <picklist>
            <controllingField>Machine_Status__c</controllingField>
            <picklistValues>
                <fullName>Smach 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 1500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 152</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 161</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 430</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Locations (Customer)</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Number__c</fullName>
        <label>Machine Number</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Machine Locations</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated-Cool Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_TriggerHandler_MI_TestClass.cls
public class FB_TriggerHandler_MI_TestClass 
{
	private static Account testAccount;
	private static Account testAccount2;
	private static Machine__c testMachine;
	private static Machine_Inventory__c testMachineInventory;
	private static Machine_Inventory__c testMachineInventory2;
	private static void init()
	{
		testAccount = FB_InitializeTestData.createAccount('FrostyBoyTestAccount');
		testAccount.Type = 'Machine Customer';
		database.insert(testAccount);
		testAccount2 = FB_InitializeTestData.createAccount('FrostyBoyTestAccount2');
		testAccount2.Type = 'Machine Customer';
		database.insert(testAccount2);
		testMachine = FB_InitializeTestData.createMachine('testMachine');
		database.insert(testMachine);
		testMachineInventory = FB_InitializeTestData.createMachineInventory(testMachine.Id,testAccount.Id);
		database.insert(testMachineInventory);
	}
	private static testMethod void insrtValdatnTestClassBI()
	{
		init();
		Test.starttest();
        try
        {
        	testMachineInventory2 = new Machine_Inventory__c();
	        testMachineInventory2.Machine_Number__c = testMachine.Id;
	        testMachineInventory2.Status__c = 'Allocated';
	        testMachineInventory2.Customer__c = testAccount2.Id;
	        database.insert(testMachineInventory2);
        }
        catch(Exception e)
        {
        	System.debug('PASS');
        }
        Test.stoptest();
	}
	private static testMethod void insrtValdatnTestClassBU()
	{
		init();
		Test.starttest();
        try
        {
        	testMachineInventory2 = new Machine_Inventory__c();
	    	testMachineInventory2.Machine_Number__c = testMachine.Id;
	        testMachineInventory2.Status__c = 'Ready';
	        testMachineInventory2.Customer__c = testAccount2.Id;
	        database.insert(testMachineInventory2);
        	testMachineInventory2.Status__c = 'Allocated';
        	database.update(testMachineInventory2);
        }
        catch(Exception e)
        {
        	System.debug('PASS2');
        }
        Test.stoptest();
	}
	private static testMethod void genMonthlPaymInactvTest()
	{
		init();
		Test.starttest();
		testMachineInventory.Status__c = 'Ready';
		database.update(testMachineInventory);
		Test.stoptest();
		
	}
}