New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Machine__c</fullName>
        <description>Please specify the machine model here</description>
        <label>Machine</label>
        <picklist>
            <controllingField>Machine_Status__c</controllingField>
            <picklistValues>
                <fullName>Smach 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 1500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 152</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 161</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 430</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Machine_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine Inventory</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_ServiceCaseCreator_TestClass.cls
@isTest(seeAllData=false)
private class FB_ServiceCaseCreator_TestClass 
{
	private static Account testAccount;
	private static Machine__c machInstance;
	private static Machine_Inventory__c machInvInstance;
	private static List<Machine__c> listOfMachines;
	private static List<Machine_Inventory__c> listOfMachineLocation;
	private static List<Case> listOfCases;
	private static void init()
	{
		testAccount = FB_InitializeTestData.createAccount('FrostyBoyTestAccount');
		testAccount.Type = 'Machine Customer';
		database.insert(testAccount);
		listOfMachines = new List<Machine__c>();
		for(Integer i=0;i<10;i++)
		{
			Machine__c testMachine = FB_InitializeTestData.createMachine('M-'+i);
			listOfMachines.add(testMachine);
		}
		database.insert(listOfMachines);
		listOfMachineLocation = new List<Machine_Inventory__c>();
		for(Machine__c instanceOfMachine:listOfMachines)
		{
			Machine_Inventory__c testMachineInventory = FB_InitializeTestData.createMachineInventory(instanceOfMachine.Id,testAccount.Id);
			listOfMachineLocation.add(testMachineInventory);
		}
		database.insert(listOfMachineLocation);
		
		
	}
	private static testMethod void testCreateCases()
	{
		init();
		Test.starttest();
        FB_ServiceCaseCreator batchApex = new FB_ServiceCaseCreator();
        ID batchprocessid= Database.executeBatch(batchApex); 
        Test.stoptest();
	}
	private static testMethod void testCreateCases2()
	{
		init();
		listOfCases = new List<Case>();
		for(Machine_Inventory__c instanceOfMachineInventory:listOfMachineLocation)
		{
			Case testCase = FB_InitializeTestData.createCase(instanceOfMachineInventory.Id);
			testCase.Reason = 'New Problem';
			listOfCases.add(testCase);
		}
		database.insert(listOfCases);
		Test.starttest();
        FB_ServiceCaseCreator batchApex = new FB_ServiceCaseCreator();
        ID batchprocessid= Database.executeBatch(batchApex); 
        Test.stoptest();
	}
	
}