New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Machine__c</fullName>
        <description>Please specify the machine model here</description>
        <label>Machine</label>
        <picklist>
            <controllingField>Machine_Status__c</controllingField>
            <picklistValues>
                <fullName>Smach 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 1500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 152</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 161</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 430</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Account_Campaign_Member__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Campaign Members</relationshipLabel>
        <relationshipName>Account_Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Account Campaign Members</relationshipLabel>
        <relationshipName>Account_Campaign_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Account Campaign Member</label>
    <nameField>
        <displayFormat>ACM-{0000}</displayFormat>
        <label>Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Machine_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine Inventory</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <fields>
        <fullName>Last_Service_Date__c</fullName>
        <label>Last Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Machine_Decals__c</fullName>
        <label>Machine Decals</label>
        <picklist>
            <controllingField>Model_Type__c</controllingField>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frosty Boy Wave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frosty Boy Bubbles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frozen Yoghurt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom Made</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model_Type__c</fullName>
        <label>Model Type</label>
        <picklist>
            <picklistValues>
                <fullName>Smach 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 1500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 152</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 161</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 430</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor C723</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classic 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preventing_M__c</fullName>
        <defaultValue>150</defaultValue>
        <label>Preventive Maintenance Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Locations (Customer)</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Number__c</fullName>
        <label>Machine Number</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Machine Locations</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated-Cool Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Monthly_Payment__c.object
<CustomObject>
    <description>This object tracks the monthly payments expected from a machine location (only if Rent/FOL). If a machine is at a location and is active , a new record is created at the start of the month using a batch class. it populates the expected revenue from that machine this month and possibly creates a task against the owner to follow up on the invoice at the end of the month.</description>
    <fields>
        <fullName>Actual_Rent__c</fullName>
        <label>Actual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Rent__c</fullName>
        <label>Expected Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Machine_Location__c</fullName>
        <label>Machine Location</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Monthly Payments</relationshipLabel>
        <relationshipName>Monthly_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <label>Monthly Payment</label>
    <nameField>
        <label>Monthly Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <picklist>
            <picklistValues>
                <fullName>Frozen Yoghurt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toppings&amp;Syrups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milk Powder Pks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UHT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Carton per year</description>
        <inlineHelpText>Please place here the estimated projection for a year</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Purchase__c.object
<CustomObject>
    <description>This object captures the details of initial costs borne by Frosty Boy to purchase machines/spare parts. ‘Purchases’ object is loosely coupled with the ‘Machines’ object to identify for which machine the purchase was made. This is being kept a separate object since spare parts would be the same (unserialized), but purchases will be made frequently.</description>
    <fields>
        <fullName>Machine__c</fullName>
        <label>Item</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_InitializeTestData.cls
global class FB_InitializeTestData
{
    public static Lead createLead()
    {
        Lead testLead = new Lead();
        testLead.LastName = 'LastName';
        testLead.Company = 'Company';
        return testLead;
    }
    public static Account createAccount(String testAccountName)
    {
        Account testAccount = new Account();
        testAccount.Name = testAccountName;
        return testAccount;
    }
    public static Opportunity createOpportunity(String testOpportunityName, Id testAccountId)
    {
        Opportunity testOpportunity = new Opportunity();
        testOpportunity.Name = testOpportunityName;
        testOpportunity.AccountId = testAccountId;
        testOpportunity.CloseDate = date.today();
        testOpportunity.StageName = 'Closed Won';
        testOpportunity.Product_Group__c = 'Beverages';
        testOpportunity.TotalOpportunityQuantity = 10000;
        testOpportunity.LeadSource = 'Cold Calling';
        testOpportunity.Description = 'Abc Def Ghi Jkl Mno Pqrs Tuv Wxyz';
        return testOpportunity;
    }
    public static Campaign createCampaign(String testCampaignName)
    {
        Campaign testCampaign = new Campaign();
        testCampaign.Name = testCampaignName;
        return testCampaign;
    }
    public static Account_Campaign_Member__c createAccountCampaignMember(String accId,String campaignId)
    {
        Account_Campaign_Member__c testACM = new Account_Campaign_Member__c();
        testACM.Campaign__c = campaignId;
        testACM.Account__c = accId;
        return testACM;
    }
    public static Machine__c createMachine(String machineSerial)
    {
        Machine__c testMachine = new Machine__c();
        testMachine.Name = machineSerial;
        testMachine.Preventing_M__c = 150;
        testMachine.Model_Type__c = 'Smach 1500';
        testMachine.Machine_Decals__c = 'Generic';
        testMachine.Last_Service_Date__c = date.newinstance(2013,01,16);
        testMachine.RecordTypeId =[select id,name from recordtype where sobjecttype='Machine__c' and name='Machine'].id;
        return testMachine;
    }
    public static Machine_Inventory__c createMachineInventory(String machineId,Id customerId)
    {
        Machine_Inventory__c testMachineInventory = new Machine_Inventory__c();
        testMachineInventory.Machine_Number__c = machineId;
        testMachineInventory.Status__c = 'Allocated';
        testMachineInventory.Customer__c = customerId;
        return testMachineInventory;
    }
    public static Monthly_Payment__c createMonthlyPayments(String machineInventoryId,String paymentName)
    {
        Monthly_Payment__c testMonthlyPayment = new Monthly_Payment__c();
        testMonthlyPayment.Name = paymentName;
        testMonthlyPayment.Machine_Location__c = machineInventoryId;
        testMonthlyPayment.Expected_Rent__c = 50.00;
        testMonthlyPayment.Actual_Rent__c = 60.00;
        testMonthlyPayment.Month__c = Date.today();
        return testMonthlyPayment;
    }
    public static Case createCase(Id inventoryId)
    {
        Case testCase = new Case();
        testCase.Machine_Inventory__c = inventoryId;
        testCase.Status='Not Started';
        testCase.Origin='Email';
        return testCase;
    }
    public static Case createCase()
    {
        Case testCase = new Case();
        testCase.Status='Not Started';
        testCase.Origin='Email';
        return testCase;
    }
    public static Purchase__c createPurchase(String SparePartId){
        Purchase__c testPurchase=new Purchase__c();
        testPurchase.Machine__c=SparePartId;
        testPurchase.Quantity__c=50;
        return testPurchase;
    }
    public static Task createTask(String whatId)
    {
    Task testTask = new Task();
    testTask.Subject= 'Call';
    testTask.WhatId= whatId;
    testTask.Description = 'Description';
    testTask.ActivityDate = date.today();
    testTask.Follow_up_Comments__c = 'abc';
    return testTask;
    }
    
    
}