New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Account_Campaign_Member__c.object
<CustomObject>
    <fields>
        <fullName>Account_Status1__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Account Campaign Member</label>
    <nameField>
        <displayFormat>ACM-{0000}</displayFormat>
        <label>Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Campaign Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_ACMUpdate_TestClass.cls
@isTest
private class FB_ACMUpdate_TestClass
{    
    static Account testAccount;
    static Campaign testCampaign;
    static Account_Campaign_Member__c testACM;
    public static void init()    
    {
        testCampaign = FB_InitializeTestData.createCampaign('Summer Trade Show');
        database.insert(testCampaign);
        testAccount = FB_InitializeTestData.createAccount('Yoghurt');
        testAccount.Account_Status__c = 'Lead';
        database.insert(testAccount);
        testACM = FB_InitializeTestData.createAccountCampaignMember(testAccount.Id,testCampaign.Id);
        testACM.Account_Status1__c = 'Lead';
        database.insert(testACM);
    }
    static testmethod void testCase()
    {
        init();
        Test.StartTest();
        testAccount.Account_Status__c = 'Active';
        database.update(testAccount);
        Test.StopTest();
    }
}