New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <description>Pick one</description>
        <label>Classification</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi Brand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclusive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub distributor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <description>Complete here if the New Account is a Lead</description>
        <label>Interested in</label>
        <picklist>
            <controllingField>Account_Status__c</controllingField>
            <picklistValues>
                <fullName>Soft-Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frozen Yoghurt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toppings and Syrups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frosty Ice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service and Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment &amp; Accessories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Notification_Mail_Sent__c</fullName>
        <label>Notification Mail Sent</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Food Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chain</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <description>You can choose up to 2 topics here.</description>
        <label>Interested in</label>
        <picklist>
            <picklistValues>
                <fullName>Soft-Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frozen Yoghurt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toppings and Syrups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frosty Ice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service and Catering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment &amp; Accessories</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/classes/NotifyAccount.cls
global class NotifyAccount
{
     
    WebService static String sendEmailNotification(String accountId) 
    {
        String messageBody;
        String emailAddress;
        Account currentAccount = [select ParentId,Phone,Primary_Email__c,Name,Interested_In__c,Classification__c,BillingPostalCode,BillingCity,BillingStreet,BillingState,BillingCountry,Description from Account where Id = :accountId];
        Contact currentContact = [select Name from Contact where AccountId = :accountId limit 1];
        Account parentAccount = [select Name,Type, primary_email__c from Account where Id = :currentAccount.ParentId];
        Messaging.SingleEmailMessage notificationMail = new Messaging.SingleEmailMessage(); 
        List<String> toAddresses = new List<String>();
        String clientAddress = '';
        if(currentAccount.BillingStreet != null){
            clientAddress  += currentAccount.BillingStreet + ' ';
        }
        if(currentAccount.BillingCity != null){
            clientAddress  += currentAccount.BillingCity + ' ';
        }
        if(currentAccount.BillingState != null){
            clientAddress  += currentAccount.BillingState + ' ';
        }
        if(currentAccount.BillingPostalCode != null){
            clientAddress  += currentAccount.BillingPostalCode + ' ';
        }
        if(currentAccount.BillingCountry != null){
            clientAddress  += currentAccount.BillingCountry + ' ';
        }
        emailAddress=(String)parentAccount.Primary_Email__c;
        toAddresses.add(emailAddress);
        notificationMail.setToAddresses(toAddresses);
        notificationMail.setSubject('New account linked to your account');
        messageBody='<html><body>Hi  '+parentAccount.Name+',<br/><br/>This mail is to inform that an account \''+ currentAccount.Name + '\' has been linked with your account. Please follow up on this lead within the next 2 business days” .<br></br>Account Information are as follows:<br/><br/> Account Name: '+ currentAccount.Name + '<br/> Address: '+ clientAddress + '<br/> Contact Name: '+ currentContact.Name + '<br/>Phone: '+ currentAccount.Phone + '<br/> Email: ' + currentAccount.Primary_Email__c + '<br/>Interested In : ' + currentAccount.Interested_In__c + '<br/> Classification: '+ currentAccount.Classification__c+ '<br/> Description: '+ currentAccount.Description +'<body></html>';
        notificationMail.setHtmlBody(messageBody);
        notificationMail.setSaveAsActivity(true);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { notificationMail});  
        currentAccount.Notification_Mail_Sent__c = 'Notification Mail Sent to Parent Account';
        update currentAccount;
        return 'success';
    }
}