New FrostyBoy Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Machine__c</fullName>
        <description>Please specify the machine model here</description>
        <label>Machine</label>
        <picklist>
            <controllingField>Machine_Status__c</controllingField>
            <picklistValues>
                <fullName>Smach 1500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 1500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smach 2500P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 152</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 161</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taylor 430</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Labour Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Machine_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine Inventory</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <fields>
        <fullName>Commissioned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Commissioned</label>
        <type>Checkbox</type>
    </fields>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <fields>
        <fullName>Cost_Till_date__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cost Till date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue_Till_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Revenue Till Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_TriggerHandler_Case_TestClass.cls
public class FB_TriggerHandler_Case_TestClass 
{
	private static Account testAccount;
	private static Case testCase;
	private static Machine__c testMachine;
	private static Machine_Inventory__c testMachineLocation;
	private static void init()
	{
		testAccount = FB_InitializeTestData.createAccount('TestAccount');
		testAccount.Type = 'Machine Customer';
		database.insert(testAccount);
		testCase = FB_InitializeTestData.createCase();
		database.insert(testCase);
		testMachine = FB_InitializeTestData.createMachine('R12333');
		database.insert(testMachine);
		testMachineLocation = FB_InitializeTestData.createMachineInventory(testMachine.Id,testAccount.Id);
		database.insert(testMachineLocation);
	}
	private static testMethod void CaseTriggerOnClose()
	{
		init();
		Test.starttest();
		testCase.Reason = 'Machine Commissioning';
        testCase.Status='Completed';
        testCase.Machine__c = testMachine.Id;
        database.update(testCase);
        Test.stoptest();
        Machine__c machIn = [select Commissioned__c from Machine__c where Id=:testMachine.Id];
        System.assertEquals(machIn.Commissioned__c, true);
	}
	private static testMethod void CaseTriggerRollupOnUpdate()
	{
		init();
		Test.starttest();
		Machine_Inventory__c machInvIn1 = [select Revenue_Till_Date__c,Cost_Till_date__c from Machine_Inventory__c where Id=:testMachineLocation.Id];
		testCase.Reason = 'Service Due';
        //testCase.Status='Completed';
        testCase.Machine_Inventory__c = testMachineLocation.Id;
        testCase.Cost__c = 5;
        testCase.Revenue__c = 10;
        database.update(testCase);
        Test.stoptest();
        Machine_Inventory__c machInvIn2 = [select Revenue_Till_Date__c,Cost_Till_date__c from Machine_Inventory__c where Id=:testMachineLocation.Id];
        System.assertNotEquals(machInvIn1.Revenue_Till_Date__c, machInvIn2.Revenue_Till_Date__c);
        System.assertNotEquals(machInvIn1.Cost_Till_date__c, machInvIn2.Cost_Till_date__c);
	}
}