New FrostyBoy Sandbox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Machine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Designations__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>User_Id__c</fullName>
        <label>User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Equipment Management Desegnations</label>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Stock__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Minimum Stock</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spare_Parts_Remaining__c</fullName>
        <formula>Total_Quantity__c - Spare_Parts_Used1__c</formula>
        <label>Spare Parts Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Spare_Parts_Used__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Spare Parts Used</relationshipLabel>
        <relationshipName>Spare_Parts_Used</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <label>Spare Part</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Spare Parts Used</relationshipLabel>
        <relationshipName>Spare_Parts_Used</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Spare Parts Used</label>
    <nameField>
        <displayFormat>SPU-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spare Parts Used</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_AddSparePartsController.cls
public class FB_AddSparePartsController {
    private final Case caseRecord;
    public Boolean showSection {get;set;}
    public Boolean showAddButton {get;set;}
    public Spare_Parts_used__c newSparePart{get;set;}
    public List<Spare_Parts_used__c> sparePartsList=new List<Spare_Parts_used__c>();
    ApexPages.StandardController sc;
    public Boolean isError {get;set;}
    public Machine__C machine;
   
    public FB_AddSparePartsController(ApexPages.StandardController controller) {
        sc=controller;
        isError=true;
        this.caseRecord = (Case)controller.getRecord();
        showSection = false;
        showAddButton = true;
    }
    public PageReference addSparePart(){
        showSection = true;
        showAddButton = false;
        newSparePart=new Spare_Parts_used__c();
        return null;
    }
    public Task newtask;
    public Boolean flag;
    
    public void addTask()
    {
        if(flag)
        database.insert(newTask);
    }
    public PageReference save(){
                
        newSparePart.case__c=caseRecord.id;
        
        flag=false;
        machine=[select id,name,spare_Parts_remaining__c,Minimum_Stock__c from Machine__c where id=:newSparePart.Spare_Part__c];
        if(machine.Spare_Parts_Remaining__c>=newSparePart.Quantity__c){
        isError=false;
        showSection = false;
        showAddButton = true;
         insert newSparePart;
         if((machine.Spare_Parts_Remaining__c-newSparePart.Quantity__c)<=machine.Minimum_Stock__c)
         {
             flag=true;
             ApexPages.Message infoMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Stock for '+machine.Name+' has gone below minimum.Please buy more stock.');
             ApexPages.addMessage(infoMsg);
             newtask = new Task();
             newTask.Subject = 'Call';
             newTask.Description= 'Stock for '+machine.name+' has gone below minimum stock required.';
             newTask.whatId = machine.Id;
             newTask.OwnerId= [select Name,User_Id__c from Designations__c where Name='Operations Manager' limit 1].User_Id__c;
             newTask.Status = 'Not Started';
             newTask.Priority = 'High';
             addTask();
        }
        // newSparePart=new Spare_Parts_used__c();
         }
        else{
        isError=true;
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'You do not have sufficient spare parts in your inventory');
        ApexPages.addMessage(myMsg);
            
        }
        
        return null;        
    }
    public List<Spare_Parts_used__c> getTableValues()
    {
        
        sparePartsList=[select Id,Name,Quantity__c,Spare_Part__c,Spare_Part__r.item__c,Spare_Part__r.Id,Spare_Part__r.Name,Case__C,CreatedDate from Spare_Parts_used__c where Case__C=:caseRecord.Id order by CreatedDate desc];
        
        return sparePartsList;
        
    }   
    public String pageURL {set;}
    public String getPageURL() {
        
    PageReference pageRef = sc.view();
    return pageRef.getUrl();    
}
  
}