New FrostyBoy Sandbox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Labour Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_incurred_on_Spare_Parts__c</fullName>
        <label>Cost incurred on Spare Parts</label>
        <summarizedField>Spare_Parts_Used__c.Cost_Incurred__c</summarizedField>
        <summaryForeignKey>Spare_Parts_Used__c.Case__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Machine_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine Inventory</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <fields>
        <fullName>Commissioned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Commissioned</label>
        <type>Checkbox</type>
    </fields>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <fields>
        <fullName>Cost_Till_date__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cost Till date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Machine_Number__c</fullName>
        <label>Machine Number</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Machine Locations</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue_Till_Date__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Revenue Till Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_TriggerHandler_Case.cls
public class FB_TriggerHandler_Case 
{
	private static FB_TriggerHandler_Case instance;
	static Map<Id,Machine_Inventory__c> machineInventoryMap;
    public static FB_TriggerHandler_Case getInstance() 
    {	
    	if (instance == null) {
    		instance = new FB_TriggerHandler_Case();
    	machineInventoryMap=new Map<Id,Machine_Inventory__c>();
    	}
        return instance;
    }
  
	public void onAfterInsert(final List<Case> newObjects) 
	{
		this.rollupCostAndRevenueAI(newObjects);
	}
	
    public void onAfterUpdate(final List<Case> oldObjects, final Map<Id, Case> oldObjectsMap,
                              final List<Case> newObjects, final Map<Id, Case> newObjectsMap) 
                              {
                                  this.setComsndTrueOnCaseClose(newObjects, oldObjectsMap);
                                  this.rollupCostAndRevenueAU(newObjects,oldObjectsMap);
                              }
    

	
    
    private void setComsndTrueOnCaseClose(final List<Case> triggerList,final Map<Id, Case> triggerOldMap)
    {
    	List<Id> listOfMachineId = new List<id>();
    	for(Case instanceOfCase:triggerList)
    	{
  			//System.debug('in1');
	      	if(instanceOfCase.Reason=='Machine Commissioning')
      		{
	        	//System.debug('in2');
	        	if( triggerOldMap.get(instanceOfCase.id).Status!=instanceOfCase.Status && instanceOfCase.Status=='Completed')
	        	{
	          		//System.debug('Check in Case - '+instanceOfCase.Id+' Commisioned '+instanceOfCase.Machine__r.Commissioned__c);
	          		listOfMachineId.add(instanceOfCase.Machine__c);
	          
	        	}
	      	}
    	}
	    if(listOfMachineId!=null)
	    {
	        List<Machine__c> listToUpdate = new List<Machine__c>();
	        for(Machine__c mach:[select Commissioned__c from Machine__c where Id IN:listOfMachineId])
	        {
		        mach.Commissioned__c = true;
		        listToUpdate.add(mach);
	        }
	        database.update(listToUpdate);
        }
    
	}
	private Map<Id,Machine_Inventory__c> rollupCostAndRevenue(final List<Case> newObjects)
	{
		//Map<Id,Machine_Inventory__c> machineInventoryMap=new Map<Id,Machine_Inventory__c>();
		List<Id> machineInventoryIds=new List<Id>();
	    for(Case c:newObjects)
	    {
	    	if(c.Machine_Inventory__c!=null)
	    	machineInventoryIds.add(c.Machine_Inventory__c);
	    }
	    for(Machine_Inventory__c m:[select id,Revenue_till_date__c,cost_till_date__c from Machine_Inventory__c where id in:machineInventoryIds])
	    {
	    	machineInventoryMap.put(m.id,m);
	    }
	    return machineInventoryMap;
	}
	private void rollupCostAndRevenueAI(final List<Case> newObjects)    
	{
		if(machineInventoryMap.size()==0)
		machineInventoryMap = this.rollupCostAndRevenue(newObjects);
		List<Machine_Inventory__c> updatedMachineInventory=new List<Machine_Inventory__c>();
		Machine_Inventory__c machineInventory;
		for(Case c:newObjects)
		{
	    	if(c.Reason=='Service Due')
	    	{
		        Decimal revenue=0,cost=0;
		        //System.debug(c.Machine_Inventory__r.revenue_till_date__c);
		        revenue=machineInventoryMap.get(c.Machine_Inventory__c).revenue_till_date__c+c.Revenue__c;
		        cost=machineInventoryMap.get(c.Machine_Inventory__c).cost_till_date__c+c.Cost__c+c.Cost_incurred_on_Spare_Parts__c;
		        machineInventory=machineInventoryMap.get(c.Machine_Inventory__c);
		        machineInventory.revenue_till_date__c=revenue;
		        machineInventory.cost_till_date__c=cost;
		        updatedMachineInventory.add(machineInventory);
	    	}
		}
		if(updatedMachineInventory.size()!=0)
	    Database.update(updatedMachineInventory);
	 }	
	 private void rollupCostAndRevenueAU(final List<Case> newObjects,final Map<Id, Case> oldObjectsMap)    
	{
		if(machineInventoryMap.size()==0)
		machineInventoryMap = this.rollupCostAndRevenue(newObjects);
		List<Machine_Inventory__c> updatedMachineInventory=new List<Machine_Inventory__c>();
		Machine_Inventory__c machineInventory;
		for(Case c:newObjects)
		{
	    	if(c.Reason=='Service Due')
	    	{
		        Decimal revenue=0,cost=0;
		        if(oldObjectsMap.get(c.id).revenue__c!= c.Revenue__c || oldObjectsMap.get(c.id).Cost__c !=c.Cost__c||oldObjectsMap.get(c.id).Cost_incurred_on_Spare_Parts__c!=c.Cost_incurred_on_Spare_Parts__c)
		        {
		        	//System.debug(machineInventoryMap.get(c.Machine_Inventory__c).revenue_till_date__c);
		        	revenue=machineInventoryMap.get(c.Machine_Inventory__c).revenue_till_date__c-oldObjectsMap.get(c.id).revenue__c+c.revenue__c;
		            cost=machineInventoryMap.get(c.Machine_Inventory__c).cost_till_date__c-oldObjectsMap.get(c.id).cost__c-oldObjectsMap.get(c.id).Cost_incurred_on_Spare_Parts__c+c.cost__c+c.Cost_incurred_on_Spare_Parts__c;
	        	}
		        machineInventory=machineInventoryMap.get(c.Machine_Inventory__c);
		        machineInventory.revenue_till_date__c=revenue;
		        machineInventory.cost_till_date__c=cost;
		        updatedMachineInventory.add(machineInventory);
	    	}
		}
		if(updatedMachineInventory.size()!=0)
	    Database.update(updatedMachineInventory);
	 }
}