New FrostyBoy Sandbox/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Machine_Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine Inventory</label>
        <referenceTo>Machine_Inventory__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Machine</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <fields>
        <fullName>Last_Service_Date__c</fullName>
        <label>Last Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Preventing_M__c</fullName>
        <defaultValue>150</defaultValue>
        <label>Preventive Maintenance Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Locations (Customer)</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Machine_Inventory1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Machine_Number__c</fullName>
        <label>Machine Number</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Machine Locations</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated-Cool Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_ServiceCaseCreator.cls
global class FB_ServiceCaseCreator implements Database.Batchable<sObject>
{
    global FB_ServiceCaseCreator ()
    {
        
    }
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        String listOfMachinesInventory = 'select Id,CreatedById,Machine_Number__c,Machine_Number__r.Last_Service_Date__c,Machine_Number__r.Preventing_M__c,Machine_Number__r.Name,Customer__c from Machine_Inventory__c where Status__c!=\'Ready\'';
        return Database.getQueryLocator(listOfMachinesInventory);
    }
    global void execute(Database.BatchableContext bc, List<Machine_Inventory__c> listOfMachinesInventory)
    {
        Set <Id> instanceIds = new Set<Id>();
        //System.debug('Rachit');
        List<Case> listOfCase = new List<Case>();
        List<Case> listOfOpencases = [select Machine_Inventory__r.Id,Id,Reason from Case where IsClosed = false];//and reason=service due
        Map<Id,Case> mapOfInventoryIdNOpenCase = new Map<Id,Case>();
        for(Case instanceOfCase:listOfOpencases)
        {
            mapOfInventoryIdNOpenCase.put(instanceOfCase.Machine_Inventory__r.Id,instanceOfCase);
        }
        for(Machine_Inventory__c instance:listOfMachinesInventory)
        {
            instanceIds=mapOfInventoryIdNOpenCase.keyset();
            //System.debug(instance.Machine_Number__r.Last_Service_Date__c.daysbetween(date.Today()));
            try
            {   
                if(instance.Machine_Number__r.Last_Service_Date__c!=null & instance.Machine_Number__r.Last_Service_Date__c.daysbetween(date.Today())>instance.Machine_Number__r.Preventing_M__c)
                {
                    if(instanceIds.contains(instance.id))
                    {
                        if(mapOfInventoryIdNOpenCase.get(instance.id).Reason!='Service Due')
                        {
                            Case caseInstance = new Case();
                            caseInstance.Machine_Inventory__c = instance.Id;
                            caseInstance.OwnerId = instance.CreatedById;//TBD
                            //caseInstance.ClosedDate = instance.Machine_Number__r.Last_Service_Date__c+150;Choose according to User
                            caseInstance.Status = 'Not Started';
                            caseInstance.Reason = 'Service Due';
                            caseInstance.Origin = 'Email';
                            caseInstance.Machine__c = instance.Machine_Number__c;
                            //caseInstance.Type = '';
                            //Either one of two - 
                            if(instance.Customer__c!=null||instance.Customer__c!='')
                            caseInstance.AccountId = instance.Customer__c;
                            else if(instance.Distributor__c!=null||instance.Distributor__c!='')
                            caseInstance.AccountId = instance.Distributor__c;
                            //Please clarify
                            caseInstance.Subject = 'Machine Due for Preventive Servicing';
                            caseInstance.Description = 'Machine Number : '+ instance.Machine_Number__r.Name +' is due for preventive servicing. Please follow up on the Machine Immediately.';
                            listOfCase.add(caseInstance);
                        }
                    }
                    else
                    {
                        Case caseInstance = new Case();
                        caseInstance.Machine_Inventory__c = instance.Id;
                        caseInstance.OwnerId = instance.CreatedById;//TBD
                        //caseInstance.ClosedDate = instance.Machine_Number__r.Last_Service_Date__c+150;Choose according to User
                        caseInstance.Status = 'Not Started';
                        caseInstance.Reason = 'Service Due';
                        caseInstance.Origin = 'Email';
                        caseInstance.Machine__c = instance.Machine_Number__c;
                        //caseInstance.Type = '';
                        caseInstance.AccountId = instance.Customer__c;
                        caseInstance.Subject = 'Machine Due for Preventive Servicing';
                        caseInstance.Description = 'Machine Number : '+ instance.Machine_Number__r.Name +' is due for preventive servicing. Please follow up on the Machine Immediately.';
                        listOfCase.add(caseInstance);
                    }
                }
                }
                catch(Exception e)
                {
                    
                }
                
        }
        database.insert(listOfCase);
    }
    global void finish(Database.BatchableContext bc)
    {
        
    }
}