New FrostyBoy Sandbox/src/objects/Machine__c.object
<CustomObject>
    <description>This object contain the details of machines and spare parts and serve as the master table for all equipment that have been purchased by  Frosty Boy.</description>
    <fields>
        <fullName>Current_Machine_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Machine Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machines</relationshipLabel>
        <relationshipName>Machines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Machine</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Machines</pluralLabel>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>This Record type will create Machine</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/objects/Machine_Inventory__c.object
<CustomObject>
    <description>This object tracks the location where a machine is kept by a distributor/Frosty Boy. All cases are raised against this record as customer location is tracked here.</description>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <formula>Contract__r.EndDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <formula>Contract__r.StartDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Machine Locations (Customer)</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistributorId__c</fullName>
        <formula>Customer__r.Parent.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DistributorId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Machine_Number__c</fullName>
        <label>Machine Number</label>
        <referenceTo>Machine__c</referenceTo>
        <relationshipLabel>Machine Locations</relationshipLabel>
        <relationshipName>Machine_Inventory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated-Cool Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Machine Location</label>
    <nameField>
        <displayFormat>MCL-{0000000000}</displayFormat>
        <label>Machine Locations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Machine Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_TriggerHandler_MachineInventory.cls
public class FB_TriggerHandler_MachineInventory 
{
		private static FB_TriggerHandler_MachineInventory instance;
		public static FB_TriggerHandler_MachineInventory getInstance()
		{
			if (instance == null) instance = new FB_TriggerHandler_MachineInventory();
        return instance;
		}
		//-- PUBLIC METHODS
		public void onBeforeInsert(final List<Machine_Inventory__c> newObjects) 
		{
			this.invntryValdatnBI(newObjects);
		}
		public void onBeforeUpdate(final List<Machine_Inventory__c> oldObjects, final Map<Id, Machine_Inventory__c> oldObjectsMap,
                               final List<Machine_Inventory__c> newObjects, final Map<Id, Machine_Inventory__c> newObjectsMap) 
                               {
                               	this.invntryValdatnBU(newObjects,oldObjectsMap);
                               }
        public void onAfterUpdate(final List<Machine_Inventory__c> oldObjects, final Map<Id, Machine_Inventory__c> oldObjectsMap,
                              final List<Machine_Inventory__c> newObjects, final Map<Id, Machine_Inventory__c> newObjectsMap) 
                              {
                              	this.genratMnthlPaymntfrInactvInvntry(newObjects,oldObjectsMap);
                              }
		public void onAfterInsert(final List<Machine_Inventory__c> newObjects, final Map<Id, Machine_Inventory__c> newObjectsMap)
		{
			
		}
		//--PRIVATE METHODS
		private Map<Id,Machine_Inventory__c> invntryValdatn(final List<Machine_Inventory__c> newObjects)
		{
			List<Id> listOfMachineId = new List<Id>();
		    Map<Id,Machine_Inventory__c> mapOfMachineIdNdName = new Map<Id,Machine_Inventory__c>();//id_name
		    for(Machine_Inventory__c machineInventoryInstance:newObjects)
		    {        
		        listOfMachineId.add(machineInventoryInstance.Machine_Number__c);     
		    }
		    //List<Machine_Inventory__c> duplicateAllocatedMachineInventory = ;
		    for(Machine_Inventory__c instanceMI:[select Machine_Number__c,Id,Name,Status__c from Machine_Inventory__c where Machine_Number__c IN:listOfMachineId AND Status__c!='Ready' order by Contract_End_Date__c desc])
		    {
		        mapOfMachineIdNdName.put(instanceMI.Machine_Number__c,instanceMI);
		    }
		    return mapOfMachineIdNdName;
		}
		private void invntryValdatnBU(final List<Machine_Inventory__c> newObjects,final Map<Id, Machine_Inventory__c> oldObjectsMap)
		{
			Map<Id,Machine_Inventory__c> mapOfMachineIdNdName = this.invntryValdatn(newObjects);
			for(Machine_Inventory__c machineInventoryInstance:newObjects)
    		{
    			/*if(mapOfMachineIdNdName.containsKey(machineInventoryInstance.Machine_Number__c) && (mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)).Name==machineInventoryInstance.Name)//Removing that particular instance out.
         		{
         			System.debug(mapOfMachineIdNdName.remove(machineInventoryInstance.Machine_Number__c));
         			Machine_Inventory__c removeUpdateInstance = mapOfMachineIdNdName.remove(machineInventoryInstance.Machine_Number__c);//removing itself from list to make sure errors dont pop while changing to status repair, allocatedcooloff.
         		}*/
         		System.debug('Checkpoint 1');
         		if(mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)!=null)
     			{
	         		System.debug(mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)+'abcd');
		            if(machineInventoryInstance.Status__c!=oldObjectsMap.get(machineInventoryInstance.Id).Status__c)
		            {
		                System.debug('in');
		                if((mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)).Id!=machineInventoryInstance.Id)
		                {
			                if(machineInventoryInstance.Status__c == 'Allocated'||machineInventoryInstance.Status__c == 'Repair'||machineInventoryInstance.Status__c == 'Allocated-Cool Off')
			                machineInventoryInstance.addError('The Machine already have '+(mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)).Status__c+' Inventory Record at location '+(mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)).Name);
		                }
		            }   
         		}
    		}       
		}
		private void invntryValdatnBI(final List<Machine_Inventory__c> newObjects)
		{
			Map<Id,Machine_Inventory__c> mapOfMachineIdNdName = this.invntryValdatn(newObjects);
			for(Machine_Inventory__c machineInventoryInstance:newObjects)
    		{
    			if(mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)!=null && (machineInventoryInstance.Status__c == 'Allocated'||machineInventoryInstance.Status__c == 'Repair'||machineInventoryInstance.Status__c == 'Allocated-Cool Off'))
         		{
            		machineInventoryInstance.addError('The Machine already have '+(mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)).Status__c+' Inventory Record at location '+(mapOfMachineIdNdName.get(machineInventoryInstance.Machine_Number__c)).Name);
         		}
    		}
		}
		private void genratMnthlPaymntfrInactvInvntry(final List<Machine_Inventory__c> newObjects,final Map<Id, Machine_Inventory__c> oldObjectsMap)
		{
			List<String> machineLocationIds=new List<String>();
      		for(Machine_Inventory__c machineLocation:newObjects)
      		{
	      		//System.debug(MachineLocation);
	      		if(machineLocation.Status__c=='Ready' && oldObjectsMap.get(machineLocation.id).status__c!='Ready')
	      		machineLocationIds.add(machineLocation.id);
      		}
      		if(!machineLocationIds.isEmpty())
      		FB_ClassGenerateMonthlyPayments.ExecuteGenerateMonthlyPayment(machineLocationIds,'Ready');
	      	//system.debug(machineLocationIds.size());
	      	
	      	Map<Id,Machine_Inventory__c> mapOfmachineIdAndStatus = new Map<Id,Machine_Inventory__c>();
	      	for(Machine_Inventory__c machineLocation:newObjects)
	      	{
	      		if(oldObjectsMap.get(machineLocation.id).status__c!=machineLocation.status__c && machineLocation.Contract_Start_Date__c<=date.today() && machineLocation.Contract_End_Date__c>=date.today())     		
	      		{
	      			mapOfmachineIdAndStatus.put(machineLocation.Machine_Number__c,machineLocation);
      			}
	      	}
	      	if(!mapOfmachineIdAndStatus.isEmpty())
	      	{
	      		for(Machine__c instanceOfMachine:[select Id from Machine__c where Id IN:mapOfmachineIdAndStatus.keyset()])
	      		{
	      			System.debug((mapOfmachineIdAndStatus.get(instanceOfMachine.Id)).Status__c+' -- New Checker On Machine Location Status');
	      			System.debug((mapOfmachineIdAndStatus.get(instanceOfMachine.Id)).Customer__c+' -- New Checker 2 On Machine Location Status');
	      			System.debug((mapOfmachineIdAndStatus.get(instanceOfMachine.Id)).DistributorId__c+' -- New Checker 2 On Machine Location Status');
	      			if((mapOfmachineIdAndStatus.get(instanceOfMachine.Id)).Status__c=='Allocated')
	      			{
	      				instanceOfMachine.Current_Machine_Location__c = (mapOfmachineIdAndStatus.get(instanceOfMachine.Id)).Customer__c;
	      			}
	      			else
	      			{
	      				System.Debug('in in in');
	      				instanceOfMachine.Current_Machine_Location__c = (mapOfmachineIdAndStatus.get(instanceOfMachine.Id)).DistributorId__c;
	      			}
	      			update instanceOfMachine;
	      		}
	      	}	
		}
		
}