New FrostyBoy Sandbox/src/objects/Monthly_Payment__c.object
<CustomObject>
    <description>This object tracks the monthly payments expected from a machine location (only if Rent/FOL). If a machine is at a location and is active , a new record is created at the start of the month using a batch class. it populates the expected revenue from that machine this month and possibly creates a task against the owner to follow up on the invoice at the end of the month.</description>
    <fields>
        <fullName>Actual_Rent__c</fullName>
        <label>Actual Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Rent__c</fullName>
        <label>Expected Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Monthly Payment</label>
    <nameField>
        <label>Monthly Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

New FrostyBoy Sandbox/src/classes/FB_SetAcutalRentAsMonthlyRent.cls
global class FB_SetAcutalRentAsMonthlyRent {
	WebService static String setActualRent(List<String> recordIds){
		//list<String> stringManipulator = new list<String>();
		string soqlQuery='Select Id,Expected_Rent__c,Actual_Rent__c from Monthly_Payment__c where Id IN (';
    	for(String a:recordIds)
    	{
    		soqlQuery=soqlQuery+'\''+a+'\',';
    	}
    	//system.debug(stringManipulator);
    	soqlQuery = soqlQuery.substring(0, soqlQuery.length()-1)+')';
		List<Monthly_Payment__c> paymentList=new List<Monthly_Payment__c>();
		
		List<Monthly_Payment__c> oldPaymentList=Database.query(soqlQuery);
			for(Monthly_Payment__c payment:oldPaymentList){
			Monthly_Payment__c newPayment=payment;
			newPayment.Actual_Rent__c=payment.Expected_Rent__c;
			system.debug(payment);
			paymentList.add(newPayment);
		}
		Database.update(paymentList);
		System.debug(paymentList);
		return 'success';
	}
}